### PR TITLE
Added three new parameters

### PR DESCRIPTION
**Pull request by palmiak**
I added three more parameters that are listed in the documentation:
```
'enqueue_style'     => 'EnqueueStyle',
'enqueue_script'    => 'EnqueueScript',
'enqueue_assets'    => 'EnqueueAssets',
```

### CODE REVIEW

**Comment by MWDelaney** [comment]
Thank you!

**Comment by tsukasa1989** [comment]
How to use the template directory in the enqueue? For example when I use: `EnqueueScript: scripts/swiper.js` then the browser tries to load http://localhost:3000/wp/scripts/swiper.js?ver=5.2.2

But this doesnt use the dist directory of the template.

**Comment by palmiak** [comment]
@tsukasa1989 you should pass the full url

**Comment by tsukasa1989** [comment]
Because the root is /wp/ you have to do /../app/themes/themename/scripts/swiper.js

Maybe there should be something like {{THEME_DIRECTORY}}/scripts/swiper.js ? Because it now depends on the theme and the directory is not generic.

**Pull request merged**
